
POST https://localhost:7154/api/Route
accept: text/plain
Content-Type: application/json

{
  "origin": "GRU",
  "destiny": "RJ",
  "value": 32
}

###

@master.bank.api_HostAddress = https://localhost:7154
# curl -X 'GET' 
#  'https://localhost:7154/api/Route?origin=GR&destiny=RJ' 
#  -H 'accept: text/plain'
GET https://localhost:7154/api/Route?origin=GRU&destiny=RJ
accept: text/plain

###


### GET request with a header
GET https://localhost:7154/api/Route?origin=GRU&destiny=SCL
Accept: application/json

