# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
    - name: Restore dependencies
      run: dotnet restore source/master.bank.galdino/master.bank.galdino.sln
    - name: Build
      run: dotnet build source/master.bank.galdino/master.bank.galdino.sln

  test:
    runs-on: ubuntu-latest
    needs: build  # Esse job depende que o "build" seja concluído com sucesso

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
    - name: Restore dependencies
      run: dotnet restore  source/master.bank.galdino/master.bank.galdino.sln # Você pode repetir o restore, ou se tiver cache, pode usar o cache
    - name: Run Tests
      run: dotnet test source/master.bank.galdino/master.bank.test/master.bank.test.csproj --no-build --verbosity normal

